name: Android

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2.3.0
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2.0.0
        with:
          path: Library
          key: Library

      # Build
      - name: Build project
        uses: webbertakken/unity-builder@v1.0
        with:
          allowDirtyBuild: false
          unityVersion: 2019.4.0f1
          targetPlatform: Android

      # Output 
      - uses: actions/upload-artifact@v1
        with:
          name: Build results
          path: build

      # Butler
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: android
          ITCH_GAME: enterthetidalzone
          ITCH_USER: thetidalzone
          PACKAGE: build